markdown: rdiscount
title: Demo Title
start_year: 2007
permalink: blog/:title
pygments: true
exclude: Makefile

navigation:
- text: Home
  url: /index.html
- text: About
  url: /about/
- text: Blog
  url: /blog/index.html
  layout: article